INFO       2016-03-15 13:16:21,786 Demodsig:
INFO       2016-03-15 13:16:21,951 Device Id 235
INFO       2016-03-15 13:16:21,990 main 320100000101000000000000000000000000000000000100000000000001000100000100040000000000000000000000000001000000000000000000000000000001000100053201000001010000000000000000000000000000000001000000000000010101000001000400000000000000000000000000000000000000000100000000000000000001000
INFO       2016-03-15 13:16:23,994 return 2160011
INFO       2016-03-15 13:16:24,032 
INFO       2016-03-15 13:21:07,552 Demodsig:
INFO       2016-03-15 13:21:07,671 Device Id 235
INFO       2016-03-15 13:21:07,723 main 320100000001000000000000000000000000000000000100000000000001000100000100040000000000000000000000000001000000000000000000000000000001000101053201000000010000000000000000000000000000000001000000000000010101000001000400000000000000000000000000000000000000000100000000000000000001010
INFO       2016-03-15 13:21:08,506 return 2160010
INFO       2016-03-15 13:21:08,556 
INFO       2016-03-15 13:23:38,625 Demodsig:
INFO       2016-03-15 13:23:38,663 Device Id 235
INFO       2016-03-15 13:23:38,700 main 320100000101000000000000000000000000000000000100000000000001000100000100040000000000000000000000000001000000000000000000000000000001000100053201000001010000000000000000000000000000000001000000000000010101000001000400000000000000000000000000000000000000000100000000000000000001000
INFO       2016-03-15 13:23:39,223 return 2160011
INFO       2016-03-15 13:23:39,266 
INFO       2016-03-15 13:35:30,677 Demodsig:
INFO       2016-03-15 13:35:30,749 Device Id 235
INFO       2016-03-15 13:35:30,786 main 10
ERROR      2016-03-15 13:35:31,078 Demodsig failed
Traceback (most recent call last):
  File "<iostream>", line 2438, in innolinks_demodsig
  File "<iostream>", line 1470, in SolveIrp
  File "<iostream>", line 1350, in Solve
IndexError: index out of range: 3
INFO       2016-03-15 13:35:31,138 
INFO       2016-03-15 14:07:27,273 Pair:
INFO       2016-03-15 14:07:27,380 Pair:
INFO       2016-03-15 14:07:27,322 Pair:
INFO       2016-03-15 14:07:28,717 Length 608 1678 4501 8934 19966 39902
INFO       2016-03-15 14:07:28,858 Length 608 1679 4502 8934 19946 39886
INFO       2016-03-15 14:07:28,999 Length 612 1674 4501 8934 19948 39898
INFO       2016-03-15 14:07:29,141 main 320100000001000000000000000000000000000000000100000000000001000100000100040000000000000000000000000001000000000000000000000000000001000101053201000000010000000000000000000000000000000001000000000000010101000001000400000000000000000000000000000000000000000100000000000000000001010
INFO       2016-03-15 14:07:29,282 main 320100000001000000000000000000000000000000000100000000000001000100000100040000000000000000000000000001000000000000000000000000000001000101053201000000010000000000000000000000000000000001000000000000010101000001000400000000000000000000000000000000000000000100000000000000000001010
INFO       2016-03-15 14:07:29,444 main 320100000001000000000000000000000000000000000100000000000001000100000100040000000000000000000000000001000000000000000000000000000001000101053201000000010000000000000000000000000000000001000000000000010101000001000400000000000000000000000000000000000000000100000000000000000001010
INFO       2016-03-15 14:14:13,437 Pair:
INFO       2016-03-15 14:14:13,872 Length 460 718 1582 1787 4257 8393
INFO       2016-03-15 14:14:14,283 main 540301010301030103010103010101010303030303030303030303030203030303010003030300030301030303030303030303030303030303030303030303030303030303030303000303031203030303030303130303030303030303030303030303031203030303030303030303030300000300030003030
ERROR      2016-03-15 14:14:43,046 Pair failed
Traceback (most recent call last):
  File "./scripts/ir.py", line 2404, in innolinks_pair
    all_x_irbs = LoadClustersFile2(cluster_file)
NameError: global name 'LoadClustersFile2' is not defined
INFO       2016-03-15 14:14:44,612 Pair:
ERROR      2016-03-15 14:14:50,470 Pair failed
Traceback (most recent call last):
  File "./scripts/ir.py", line 2404, in innolinks_pair
    all_x_irbs = LoadClustersFile2(cluster_file)
NameError: global name 'LoadClustersFile2' is not defined
INFO       2016-03-15 14:14:50,885 Pair:
INFO       2016-03-15 14:14:52,556 
INFO       2016-03-15 14:14:52,697 Length 643 1635
INFO       2016-03-15 14:14:52,943 
INFO       2016-03-15 14:14:53,272 Length 534 1460 4061 8384
INFO       2016-03-15 14:14:53,477 main 01010101010101010100000100010001010
INFO       2016-03-15 14:14:53,743 main 320001010001000100010100010101010000000000000000000000000000000000010100000001000001000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000001010001000100000
INFO       2016-03-17 18:01:46,813 Pair:
INFO       2016-03-17 18:01:46,691 Pair:
INFO       2016-03-17 18:01:48,653 Length 525 726 1736 1943 4587 8927 19952 39842
INFO       2016-03-17 18:01:48,845 Length 206 498 699 909 1764 20097
INFO       2016-03-17 18:01:49,141 main 540200000202000000000000000001000000000000000200000000000002000200000200060000000000000000000000000002000000000000000000000000000002000200075402000002020000000000000000000000000000000002000000000000020202000002000600000000000000000000000101010000000000000201010101000100000003000
INFO       2016-03-17 18:01:49,358 main 1212121114141412121412151212121112121211121212121212121212121211141213021212121212111
INFO       2016-03-17 18:03:36,161 Pair:
INFO       2016-03-17 18:03:36,719 Length 606 1680 4506 8949 19940 39880
INFO       2016-03-17 18:03:37,283 main 320100000001000000000000000000000000000000000100000000000001000100000100040000000000000000000000000001000000000000000000000000000001000101053201000000010000000000000000000000000000000001000000000000010101000001000400000000000000000000000000000000000000000100000000000000000001010
INFO       2016-03-17 18:08:44,500 Pair:
INFO       2016-03-17 18:08:45,072 Length 498 1639 4353 4430 5262
INFO       2016-03-17 18:08:45,696 main 2301000101000001000001000001010001000101010100010101000000000100000101010000000000000000010101010104220100010100000100000100000101000100010101010001010100000000010000010101000000000000000001010101010
INFO       2016-03-17 18:10:16,723 Pair:
INFO       2016-03-17 18:10:17,213 Length 442 678 1694 4275 4506 5213
INFO       2016-03-17 18:10:17,786 main 3402000202000002000002000102020002020002020202020200020000000000000202020000020000000000020200020205330201020200000200000200000202000202000202020202020002000000000000020202000002000000000002020002020
INFO       2016-03-17 18:11:06,769 Pair:
INFO       2016-03-17 18:11:07,770 Length 547 1590 4377 4384 5181
INFO       2016-03-17 18:11:08,450 main 3201000101000001000001000001010001010001010101010100010000000000000101010000010000000000010100010104330100010100000100000100000101000101000101010101010001000000000000010101000001000000000001010001010
INFO       2016-03-17 18:11:18,375 Pair:
INFO       2016-03-17 18:11:18,934 Length 581 1556 4344 4413 5177
INFO       2016-03-17 18:11:19,509 main 3201000101000001000001000001010001000101010100010101000000000100000101010000000000000000010101010104330100010100000100000100000101000100010101010001010100000000010000010101000000000000000001010101010
ERROR      2016-03-17 18:11:23,190 Pair failed
Traceback (most recent call last):
  File "./scripts/ir.py", line 2407, in innolinks_pair
    device_id = int(ids[0].split("-")[0], 10)
IndexError: index out of range: 0
INFO       2016-03-17 18:11:33,907 
INFO       2016-03-17 18:12:02,637 return 235
INFO       2016-03-17 18:12:03,058 
INFO       2016-03-17 18:13:25,394 return 235
INFO       2016-03-17 18:13:25,937 
INFO       2016-03-18 13:49:59,688 Demodsig:
INFO       2016-03-18 13:49:59,848 Device Id 235
INFO       2016-03-18 13:49:59,885 main 320100000100000000010000010000000000000000000100000000000001000100000100040000000000000000000000000001000000000000000000000000000000010101053201000001000000000100000100000000000000000001000000000000010101000001000400000000000000000000000000000000000000000000000000000000000001010
INFO       2016-03-18 13:50:01,973 return 2250061
INFO       2016-03-18 13:50:02,010 
